DROP DATABASE IF EXISTS `strona`;
CREATE DATABASE IF NOT EXISTS `strona`;
USE `strona`;


DROP TABLE IF EXISTS `szablony`;
CREATE TABLE IF NOT EXISTS `szablony` (
  `nazwa` varchar(15) NOT NULL,
  `tekst` varchar(5000) NOT NULL,
  PRIMARY KEY (`nazwa`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DELETE FROM `szablony`;
INSERT INTO `szablony` (`nazwa`, `tekst`) VALUES
	('s1s1', 'html, body\r\n{\r\n  margin: 0;\r\n  padding: 0;\r\n  background: '),
	('s1s2', '; /* color 4*/\r\n}\r\n\r\n.nav\r\n{\r\n  position: fixed;\r\n  width: 100%;\r\n  top: 0;\r\n  left: 0;\r\n  z-index: 999;\r\n  background: '),
	('s1s3', '; /* color 1*/\r\n  padding: 8px 8px;\r\n}\r\n\r\n.smoothscroll /*menu btns*/\r\n{\r\n    background-color: '),
	('s1s4', '; /* Color 2 */\r\n    border: none;\r\n    color: '),
	('s1s5', '; /* color 3 */\r\n    padding: 15px 32px;\r\n    text-align: center;\r\n    text-decoration: none;\r\n    display: inline-block;\r\n    font-size: 18px;\r\n}\r\n\r\n.content\r\n{\r\n  width: 80%;\r\n  height: 400%;\r\n  margin: 0 10% 0 10%;\r\n  position: relative;\r\n  background-color: '),
	('s1s6', '; /* color 5*/\r\n  background-repeat: no-repeat;\r\n  background-size: cover;\r\n  color: '),
	('s1s7', '; /* color 3 */\r\n}\r\n\r\n.p1\r\n{\r\n	height: 100vh;\r\n	poition: static;\r\n	margin: 48px 0 0 0;\r\n}\r\n.p2\r\n{\r\n	height: 100vh;\r\n	poition: absolute;\r\n	margin: 48px 0 0 0;\r\n}\r\n.p3\r\n{\r\n	height: 100vh;\r\n	poition: absolute;\r\n	margin: 48px 0 0 0;\r\n}\r\n.p4\r\n{\r\n	height: 100vh;\r\n	poition: absolute;\r\n	margin: 48px 0 0 0;\r\n}\r\n.p5\r\n{\r\n	height: 100vh;\r\n	poition: absolute;\r\n	margin: 48px 0 0 0;\r\n}\r\n.spacer\r\n{\r\n    margin: 0 0 48px 0;\r\n    position: absolute;\r\n}'),
	('s1_p1', '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">\r\n<head>\r\n      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\r\n      <title>Tytuł</title>\r\n      <link rel="stylesheet" type="text/css" href="style.css">\r\n      <script src="jquery-3.1.1.min.js"></script>\r\n</head>\r\n\r\n<body>\r\n<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>\r\n<script>\r\n$(\'.smoothscroll\').on(\'click\', function (e) {\r\n	 	\r\n	 	e.preventDefault();\r\n\r\n   	var target = this.hash;        \r\n\r\n    	$(\'html,body\').animate({\r\n          scrollTop: $(target).offset().top\r\n        }, 500, "swing");\r\n      });\r\n\r\n  	}); \r\n</script>\r\n\r\n<div class="nav">\r\n    <a href="#jeden" class="smoothscroll">Aktualności</a>\r\n    <a href="#dwa" class="smoothscroll">Sekcje</a>\r\n    <a href="#trzy" class="smoothscroll">Kadra</a>\r\n    <a href="#cztery" class="smoothscroll">O nas</a>\r\n    <a href="#piec" class="smoothscroll">Kontakt</a>\r\n</div>\r\n\r\n<div class = "content"> \r\n\r\n\r\n    <div class = "spcer" id="jeden">&nbsp;</div>\r\n	<section class="p1">\r\n	<h1>Aktualności</h1>'),
	('s1_p2', '\r\n	</section>\r\n    <div class = "spcer" id="dwa">&nbsp;</div>\r\n	<section class="p2">\r\n	<h1>Sekcje</h1>'),
	('s1_p3', '\r\n	</section>\r\n    <div class = "spcer" id="trzy">&nbsp;</div>\r\n	<section class="p3">\r\n	<h1>Kadra</h1>'),
	('s1_p4', '\r\n	</section>\r\n    <div class = "spcer" id="cztery">&nbsp;</div>\r\n	<section class="p4">\r\n	<h1>O nas</h1>'),
	('s1_p5', '\r\n	</section>\r\n    <div class = "spcer" id="piec">&nbsp;</div>\r\n	<section class="p5">\r\n	<h1>Kontakt</h1>'),
	('s1_p6', '\r\n	</section>\r\n\r\n</div>\r\n\r\n</body>\r\n</html>'),
	('s1_scr', 'jQuery(document).ready(function($) {\r\n \r\n	$(".scroll").click(function(event){		\r\n		event.preventDefault();\r\n		$(\'html,body\').animate({scrollTop:$(this.hash).offset().top}, 500);\r\n	});\r\n});'),
	('s1_style', 'html, body\r\n{\r\n  margin: 0;\r\n  padding: 0;\r\n  background: rgb(240, 248, 255); /* Fall-back for browsers that don\'t\r\n                                    support rgba */\r\n  background: rgba(240, 248, 255, 0.3);\r\n}\r\n\r\n.nav\r\n{\r\n  position: fixed;\r\n  width: 100%;\r\n  top: 0;\r\n  left: 0;\r\n  z-index: 999;\r\n  background: rgb(0, 191, 255); /* Fall-back for browsers that don\'t\r\n                                    support rgba */\r\n  background: rgba(0, 191, 255, 0.6);\r\n  padding: 8px 8px;\r\n}\r\n\r\n.smoothscroll /*menu btns*/\r\n{\r\n    background-color: #00BFFF; /* Green */\r\n    border: none;\r\n    color: blue;\r\n    padding: 15px 32px;\r\n    text-align: center;\r\n    text-decoration: none;\r\n    display: inline-block;\r\n    font-size: 18px;\r\n}\r\n\r\n.content\r\n{\r\n  width: 80%;\r\n  height: 400%;\r\n  margin: 0 10% 0 10%;\r\n  position: relative;\r\n  background-color: #F0F8FF;\r\n  background-repeat: no-repeat;\r\n  background-size: cover;\r\n  color: blue;\r\n}\r\n\r\n.p1\r\n{\r\n	height: 100vh;\r\n	poition: static;\r\n	margin: 48px 0 0 0;\r\n}\r\n.p2\r\n{\r\n	height: 100vh;\r\n	poition: absolute;\r\n	margin: 48px 0 0 0;\r\n}\r\n.p3\r\n{\r\n	height: 100vh;\r\n	poition: absolute;\r\n	margin: 48px 0 0 0;\r\n}\r\n.p4\r\n{\r\n	height: 100vh;\r\n	poition: absolute;\r\n	margin: 48px 0 0 0;\r\n}\r\n.p5\r\n{\r\n	height: 100vh;\r\n	poition: absolute;\r\n	margin: 48px 0 0 0;\r\n}\r\n.spacer\r\n{\r\n    margin: 0 0 48px 0;\r\n    position: absolute;\r\n}'),
	('s1_style1', 'html, body\r\n{\r\n  margin: 0;\r\n  padding: 0;\r\n  background: rgb(255, 218, 185); /* Fall-back for browsers that don\'t\r\n                                    support rgba */\r\n  background: rgba(255, 218, 185, 0.3);\r\n}\r\n\r\n.nav\r\n{\r\n  position: fixed;\r\n  width: 100%;\r\n  top: 0;\r\n  left: 0;\r\n  z-index: 999;\r\n  background: rgb(255, 140, 0); /* Fall-back for browsers that don\'t\r\n                                    support rgba */\r\n  background: rgba(255, 140, 0, 0.6);\r\n  padding: 8px 8px;\r\n}\r\n\r\n.smoothscroll /*menu btns*/\r\n{\r\n    background-color: #FF8C00; /* Green */\r\n    border: none;\r\n    color: #FFFFF0;\r\n    padding: 15px 32px;\r\n    text-align: center;\r\n    text-decoration: none;\r\n    display: inline-block;\r\n    font-size: 18px;\r\n}\r\n\r\n.content\r\n{\r\n  width: 80%;\r\n  height: 400%;\r\n  margin: 0 10% 0 10%;\r\n  position: relative;\r\n  background-color: #FFDAB9;\r\n  background-repeat: no-repeat;\r\n  background-size: cover;\r\n  color: Saddlebrown;\r\n}\r\n\r\n.p1\r\n{\r\n	height: 100vh;\r\n	poition: static;\r\n	margin: 48px 0 0 0;\r\n}\r\n.p2\r\n{\r\n	height: 100vh;\r\n	poition: absolute;\r\n	margin: 48px 0 0 0;\r\n}\r\n.p3\r\n{\r\n	height: 100vh;\r\n	poition: absolute;\r\n	margin: 48px 0 0 0;\r\n}\r\n.p4\r\n{\r\n	height: 100vh;\r\n	poition: absolute;\r\n	margin: 48px 0 0 0;\r\n}\r\n.p5\r\n{\r\n	height: 100vh;\r\n	poition: absolute;\r\n	margin: 48px 0 0 0;\r\n}\r\n.spacer\r\n{\r\n    margin: 0 0 48px 0;\r\n    position: absolute;\r\n}'),
	('s2s1', 'html, body\r\n{\r\n	margin: 0;\r\n	padding: 0;\r\n    background: '),
	('s2s2', '; /* color 4*/\r\n}\r\n\r\n.head\r\n{\r\n  position: absolute;\r\n  width: 100%;\r\n  height: 15%;\r\n  background-image: url("tlo.png");\r\n}\r\n\r\n.nav\r\n{\r\n  position: absolute;\r\n  top: 15%;\r\n  width: 100%;\r\n  height: 6%;\r\n  padding-top: 4px;\r\n  padding-bottom: 4px;\r\n  background: '),
	('s2s3', '; /* color 1*/\r\n}\r\n\r\n.nav_btn\r\n{\r\n    background-color: '),
	('s2s4', '; /* Color 2 */\r\n    border: none;\r\n    color: '),
	('s2s5', '; /* color 3 */\r\n    padding: 15px 32px;\r\n    text-align: center;\r\n    text-decoration: none;\r\n    display: inline-block;\r\n    font-size: 18px;\r\n}\r\n\r\n.container\r\n{\r\n  width: 80%;\r\n  height: 100%;\r\n  position: fixed;\r\n  margin: 0 10% 0 10%;\r\n  background-color: '),
	('s2s6', '; /* color 5*/\r\n  background-repeat: no-repeat;\r\n  background-size: cover;\r\n  color: '),
	('s2s7', '; /* color 3 */\r\n}\r\n\r\n.content\r\n{\r\n  position: fixed;\r\n  width: 60%;\r\n  height: 100%;\r\n  top: 22%;\r\n  left: 10%;\r\n  right: 20%;\r\n  background-color: transparent;\r\n  float: left;\r\n}\r\n\r\n.content_right\r\n{\r\n  position: fixed;\r\n  width: 20%;\r\n  height: 100%;\r\n  top: 22%;\r\n  left: 70%;\r\n  right: 20%;\r\n  background-color: transparent;\r\n  float: left;\r\n}\r\n'),
	('s2_1', '<h1>Aktualności</h1>'),
	('s2_2', '<h1>Sekcje</h1>'),
	('s2_3', '<h1>Kadra</h1>'),
	('s2_4', '<h1>O nas</h1>'),
	('s2_5', '<h1>Kontakt</h1>'),
	('s2_index', '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">\r\n<head>\r\n      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\r\n      <title>Tytuł</title>\r\n      <link rel="stylesheet" type="text/css" href="style.css">\r\n</head>\r\n\r\n<body>\r\n<!-- \r\n<div class="nav">\r\n    <a href="#jeden" id="left" class = "nav_btn">Jeden</a>\r\n    <a href="#dwa" id="middle" class = "nav_btn">Dwa</a>\r\n    <a href="#trzy" id="right" class = "nav_btn">Trzy</a>\r\n<div/>\r\n -->\r\n \r\n<div class = "container"> <!-- start całego cointainera -->\r\n    <div  class = "head">\r\n    </div> \r\n    <div  class = "nav">\r\n    <a href="index.php?menu=1" class = "nav_btn">Aktualności</a>\r\n    <a href="index.php?menu=2" class = "nav_btn">Sekcje</a>\r\n    <a href="index.php?menu=3" class = "nav_btn">Kadra</a>  \r\n    <a href="index.php?menu=4" class = "nav_btn">O nas</a>  \r\n    </div>\r\n\r\n    <div id="content" class = "content"> \r\n<?php\r\n\r\nif (!isset($_GET[\'menu\']))\r\n    include(\'1.html\');\r\nelse\r\n{    \r\n    $arg = (int)$_GET[\'menu\'];\r\n     \r\n    switch ($arg)\r\n    {\r\n        case 1:\r\n            include(\'1.html\');\r\n        break;\r\n     \r\n        case 2:\r\n            include(\'2.html\');\r\n        break;\r\n     \r\n        case 3:\r\n            include(\'3.html\');\r\n        break;\r\n        \r\n        case 4:\r\n            include(\'4.html\');\r\n        break;\r\n     \r\n        default:\r\n            include(\'1.html\');\r\n        break;\r\n    }\r\n}\r\n \r\n?>\r\n    </div>\r\n    \r\n    <div id = "content_r" class = "content_right"> \r\n    <?php\r\n    include(\'5.html\');\r\n    ?>\r\n    </div>\r\n    \r\n</div> <!-- koniec całego cointainera -->\r\n\r\n</body>\r\n</html>\r\n'),
	('s2_style', 'html, body\r\n{\r\n	margin: 0;\r\n	padding: 0;\r\n    background: rgb(240, 248, 255); /* Fall-back for browsers that don\'t\r\n                                    support rgba */\r\n    background: rgba(240, 248, 255, 0.3);\r\n}\r\n\r\n.head\r\n{\r\n  position: absolute;\r\n  width: 100%;\r\n  height: 15%;\r\n  background-image: url("tlo.png");\r\n}\r\n\r\n.nav\r\n{\r\n  position: absolute;\r\n  top: 15%;\r\n  width: 100%;\r\n  height: 6%;\r\n  padding-top: 4px;\r\n  padding-bottom: 4px;\r\n  background: rgb(0, 191, 255); /* Fall-back for browsers that don\'t\r\n                                    support rgba */\r\n  background: rgba(0, 191, 255, 0.6);\r\n}\r\n\r\n.nav_btn\r\n{\r\n    background-color: #00BFFF; /* Green */\r\n    border: none;\r\n    color: blue;\r\n    padding: 15px 32px;\r\n    text-align: center;\r\n    text-decoration: none;\r\n    display: inline-block;\r\n    font-size: 18px;\r\n}\r\n\r\n.container\r\n{\r\n  width: 80%;\r\n  height: 100%;\r\n  position: fixed;\r\n  margin: 0 10% 0 10%;\r\n  background-color: #F0F8FF;\r\n  background-repeat: no-repeat;\r\n  background-size: cover;\r\n  color: blue;\r\n}\r\n\r\n.content\r\n{\r\n  position: fixed;\r\n  width: 60%;\r\n  height: 100%;\r\n  top: 22%;\r\n  left: 10%;\r\n  right: 20%;\r\n  background-color: transparent;\r\n  float: left;\r\n}\r\n\r\n.content_right\r\n{\r\n  position: fixed;\r\n  width: 20%;\r\n  height: 100%;\r\n  top: 22%;\r\n  left: 70%;\r\n  right: 20%;\r\n  background-color: transparent;\r\n  float: left;\r\n}\r\n'),
	('s2_style1', 'html, body\r\n{\r\n	margin: 0;\r\n	padding: 0;\r\n  background: rgb(255, 218, 185); /* Fall-back for browsers that don\'t\r\n                                    support rgba */\r\n  background: rgba(255, 218, 185, 0.3);\r\n}\r\n\r\n.head\r\n{\r\n  position: absolute;\r\n  width: 100%;\r\n  height: 15%;\r\n  background-image: url("tlo.png");\r\n}\r\n\r\n.nav\r\n{\r\n  position: absolute;\r\n  top: 15%;\r\n  width: 100%;\r\n  height: 6%;\r\n  padding-top: 4px;\r\n  padding-bottom: 4px;\r\n  background: rgb(255, 140, 0); /* Fall-back for browsers that don\'t\r\n                                    support rgba */\r\n  background: rgba(255, 140, 0, 0.6);\r\n}\r\n\r\n.nav_btn\r\n{\r\n    background-color: #FF8C00; /* Green */\r\n    border: none;\r\n    color: #FFFFF0;\r\n    padding: 15px 32px;\r\n    text-align: center;\r\n    text-decoration: none;\r\n    display: inline-block;\r\n    font-size: 18px;\r\n}\r\n\r\n.container\r\n{\r\n  width: 80%;\r\n  height: 100%;\r\n  position: fixed;\r\n  margin: 0 10% 0 10%;\r\n  background-color: #FFDAB9;\r\n  background-repeat: no-repeat;\r\n  background-size: cover;\r\n  color: Saddlebrown;\r\n}\r\n\r\n.content\r\n{\r\n  position: fixed;\r\n  width: 60%;\r\n  height: 100%;\r\n  top: 22%;\r\n  left: 10%;\r\n  right: 20%;\r\n  background-color: transparent;\r\n  float: left;\r\n}\r\n\r\n.content_right\r\n{\r\n  position: fixed;\r\n  width: 20%;\r\n  height: 100%;\r\n  top: 22%;\r\n  left: 70%;\r\n  right: 20%;\r\n  background-color: transparent;\r\n  float: left;\r\n}\r\n'),
	('s3s1', 'html, body\r\n{\r\n	margin: 0;\r\n	padding: 0;\r\n    background: '),
	('s3s2', '; /* color 4*/\r\n}\r\n\r\n.head\r\n{\r\n  position: fixed;\r\n  width: 100%;\r\n  height: 15%;\r\n  background-image: url("tlo.png");\r\n}\r\n\r\n.nav\r\n{\r\n  position: fixed;\r\n  top: 15%;\r\n  width: 100%;\r\n  height: 6%;\r\n  padding: 8px 8px;\r\n  background: '),
	('s3s3', '; /* color 1*/\r\n}\r\n\r\n.nav_btn\r\n{\r\n    background-color: '),
	('s3s4', '; /* Color 2 */\r\n    border: none;\r\n    color: '),
	('s3s5', '; /* color 3 */\r\n    padding: 15px 32px;\r\n    text-align: center;\r\n    text-decoration: none;\r\n    display: inline-block;\r\n    font-size: 18px;\r\n}\r\n\r\n.container\r\n{\r\n  width: 80%;\r\n  height: 80%;\r\n  top:23%;\r\n  position: fixed;\r\n  margin: 0 10% 0 10%;\r\n  background-color: '),
	('s3s6', '; /* color 5*/\r\n  background-repeat: no-repeat;\r\n  background-size: cover;\r\n  color: '),
	('s3s7', '; /* color 3 */\r\n}\r\n\r\n.content\r\n{\r\n  position: fixed;\r\n  width: 60%;\r\n  height: 100%;\r\n  top: 23%;\r\n  left: 10%;\r\n  right: 20%;\r\n  background-color: transparent;\r\n  float: left;\r\n}\r\n'),
	('s3_1', '<h1>Aktualności</h1>'),
	('s3_2', '<h1>Sekcje</h1>'),
	('s3_3', '<h1>Kadra</h1>'),
	('s3_4', '<h1>O nas</h1>'),
	('s3_5', '<h1>Kontakt</h1>'),
	('s3_index', '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">\r\n<head>\r\n      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\r\n      <title>Tytuł</title>\r\n      <link rel="stylesheet" type="text/css" href="style.css">\r\n</head>\r\n\r\n<body>\r\n<!-- \r\n<div class="nav">\r\n    <a href="#jeden" id="left" class = "nav_btn">Jeden</a>\r\n    <a href="#dwa" id="middle" class = "nav_btn">Dwa</a>\r\n    <a href="#trzy" id="right" class = "nav_btn">Trzy</a>\r\n<div/>\r\n -->\r\n \r\n<div  class = "head">\r\n\r\n</div> \r\n<div  class = "nav">\r\n    <a href="index.php?menu=1" class = "nav_btn">Aktualności</a>\r\n    <a href="index.php?menu=2" class = "nav_btn">Sekcje</a>\r\n    <a href="index.php?menu=3" class = "nav_btn">Kadra</a>  \r\n    <a href="index.php?menu=4" class = "nav_btn">O nas</a> \r\n    <a href="index.php?menu=5" class = "nav_btn">Kontakt</a>   \r\n</div>\r\n \r\n<div class = "container"> <!-- start całego cointainera -->\r\n    \r\n    <div class = "content"> \r\n    <?php\r\n    if (!isset($_GET[\'menu\']))\r\n        include(\'1.html\');\r\n    else\r\n    {    \r\n        $arg = (int)$_GET[\'menu\'];\r\n         \r\n        switch ($arg)\r\n        {\r\n            case 1:\r\n                include(\'1.html\');\r\n            break;\r\n         \r\n            case 2:\r\n                include(\'2.html\');\r\n            break;\r\n         \r\n            case 3:\r\n                include(\'3.html\');\r\n            break;\r\n            \r\n            case 4:\r\n                include(\'4.html\');\r\n            break;\r\n            \r\n            case 5:\r\n                include(\'5.html\');\r\n            break;\r\n         \r\n            default:\r\n                include(\'1.html\');\r\n            break;\r\n        }\r\n    }     \r\n    ?>\r\n    </div>\r\n    \r\n</div> <!-- koniec całego cointainera -->\r\n\r\n</body>\r\n</html>\r\n\r\n'),
	('s3_style', '\r\nhtml, body\r\n{\r\n	margin: 0;\r\n	padding: 0;\r\n    background: rgb(240, 248, 255); /* Fall-back for browsers that don\'t\r\n                                    support rgba */\r\n    background: rgba(240, 248, 255, 0.3);\r\n}\r\n\r\n.head\r\n{\r\n  position: fixed;\r\n  width: 100%;\r\n  height: 15%;\r\n  background-image: url("tlo.png");\r\n}\r\n\r\n.nav\r\n{\r\n  position: fixed;\r\n  top: 15%;\r\n  width: 100%;\r\n  height: 6%;\r\n  padding: 8px 8px;\r\n  background-color: #DCDCDC;\r\n  background: rgb(0, 191, 255); /* Fall-back for browsers that don\'t\r\n                                    support rgba */\r\n  background: rgba(0, 191, 255, 0.6);\r\n}\r\n\r\n.nav_btn\r\n{\r\n    background-color: #00BFFF; /* Green */\r\n    border: none;\r\n    color: blue;\r\n    padding: 15px 32px;\r\n    text-align: center;\r\n    text-decoration: none;\r\n    display: inline-block;\r\n    font-size: 18px;\r\n}\r\n\r\n.container\r\n{\r\n  width: 80%;\r\n  height: 80%;\r\n  top:23%;\r\n  position: fixed;\r\n  margin: 0 10% 0 10%;\r\n  background-color: #F0F8FF;\r\n  background-repeat: no-repeat;\r\n  background-size: cover;\r\n  color: blue;\r\n}\r\n\r\n.content\r\n{\r\n  position: fixed;\r\n  width: 60%;\r\n  height: 100%;\r\n  top: 23%;\r\n  left: 10%;\r\n  right: 20%;\r\n  background-color: transparent;\r\n  float: left;\r\n}\r\n'),
	('s3_style1', '\r\nhtml, body\r\n{\r\n	margin: 0;\r\n	padding: 0;\r\n    background: rgb(255, 218, 185); /* Fall-back for browsers that don\'t\r\n                                    support rgba */\r\n    background: rgba(255, 218, 185, 0.3);\r\n}\r\n\r\n.head\r\n{\r\n  position: fixed;\r\n  width: 100%;\r\n  height: 15%;\r\n  background-image: url("tlo.png");\r\n}\r\n\r\n.nav\r\n{\r\n  position: fixed;\r\n  top: 15%;\r\n  width: 100%;\r\n  height: 6%;\r\n  padding: 8px 8px;\r\n  background: rgb(255, 140, 0); /* Fall-back for browsers that don\'t\r\n                                    support rgba */\r\n  background: rgba(255, 140, 0, 0.6);\r\n  padding: 8px 8px;\r\n}\r\n\r\n.nav_btn\r\n{\r\n    background-color: #FF8C00; /* Green */\r\n    border: none;\r\n    color: #FFFFF0;\r\n    padding: 15px 32px;\r\n    text-align: center;\r\n    text-decoration: none;\r\n    display: inline-block;\r\n    font-size: 18px;\r\n}\r\n\r\n.container\r\n{\r\n  width: 80%;\r\n  height: 80%;\r\n  top:23%;\r\n  position: fixed;\r\n  margin: 0 10% 0 10%;\r\n  background-color: #FFDAB9;\r\n  background-repeat: no-repeat;\r\n  background-size: cover;\r\n  color: Saddlebrown;\r\n}\r\n\r\n.content\r\n{\r\n  position: fixed;\r\n  width: 60%;\r\n  height: 100%;\r\n  top: 23%;\r\n  left: 10%;\r\n  right: 20%;\r\n  background-color: transparent;\r\n  float: left;\r\n}\r\n'),
	('s4s1', '\r\nhtml, body\r\n{\r\n	margin: 0;\r\n	padding: 0;\r\n    background: '),
	('s4s2', '; /* color 4*/\r\n}\r\n\r\n.head\r\n{\r\n  position: fixed;\r\n  width: 100%;\r\n  height: 15%;\r\n}\r\n\r\n.nav\r\n{\r\n  position: fixed;\r\n  width: 100%;\r\n  height: 6%;\r\n  background-color: '),
	('s4s3', '; /* color 1 */\r\n  padding: 8px 8px;\r\n}\r\n\r\n.nav_btn\r\n{\r\n    background-color: '),
	('s4s4', '; /* Color 2 */\r\n    border: none;\r\n    color: '),
	('s4s5', '; /* color 3 */\r\n    padding: 15px 32px;\r\n    text-align: center;\r\n    text-decoration: none;\r\n    display: inline-block;\r\n    font-size: 18px;\r\n}\r\n\r\n.container\r\n{\r\n  width: 80%;\r\n  height: 90%;\r\n  top:14%;\r\n  position: fixed;\r\n  margin: 0 10% 0 10%;\r\n  background-color: '),
	('s4s6', '; /* color 5*/\r\n  background-repeat: no-repeat;\r\n  background-size: cover;\r\n  color: '),
	('s4s7', '; /* color 3 */\r\n} \r\n\r\n.submenu\r\n{\r\n  top: 8%;\r\n  height: 3%;\r\n  width: 100%;\r\n  position: fixed;\r\n  background-color: '),
	('s4s8', '; /* color 1 */\r\n  color: '),
	('s4s9', '; /* Color 2 */\r\n  font-size: 28px;\r\n  font-family: Courier new;\r\n  text-align: left;\r\n  padding: 1%;\r\n}\r\n\r\n.content\r\n{\r\n  position: fixed;\r\n  width: 60%;\r\n  height: 100%;\r\n  top: 14%;\r\n  left: 10%;\r\n  right: 20%;\r\n  background-color: transparent;\r\n  float: left;\r\n}\r\n'),
	('s4_1', '<h1>Aktualności</h1>'),
	('s4_2', '<h1>Sekcje</h1>'),
	('s4_3', '<h1>Kadra</h1>'),
	('s4_4', '<h1>O nas</h1>'),
	('s4_5', '<h1>Kontakt</h1>'),
	('s4_index', '\r\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">\r\n<head>\r\n      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\r\n      <title>Tytuł</title>\r\n      <link rel="stylesheet" type="text/css" href="style.css">\r\n</head>\r\n\r\n<body>\r\n<!-- \r\n<div class="nav">\r\n    <a href="#jeden" id="left" class = "nav_btn">Jeden</a>\r\n    <a href="#dwa" id="middle" class = "nav_btn">Dwa</a>\r\n    <a href="#trzy" id="right" class = "nav_btn">Trzy</a>\r\n<div/>\r\n -->\r\n\r\n<div class = "nav">\r\n    <a href="index.php?menu=1" class = "nav_btn">Aktualności</a>\r\n    <a href="index.php?menu=2" class = "nav_btn">Sekcje</a>\r\n    <a href="index.php?menu=3" class = "nav_btn">Kadra</a>  \r\n    <a href="index.php?menu=4" class = "nav_btn">O nas</a> \r\n    <a href="index.php?menu=5" class = "nav_btn">Kontakt</a>    \r\n</div>\r\n \r\n \r\n<div class = "submenu">\r\n<?php\r\n    if (!isset($_GET[\'menu\']))\r\n        echo "Aktualności";\r\n    else\r\n    {    \r\n        $arg = (int)$_GET[\'menu\'];\r\n         \r\n        switch ($arg)\r\n        {\r\n            case 1:\r\n                echo "Aktualności";\r\n            break;\r\n         \r\n            case 2:\r\n                echo "Sekcje";\r\n            break;\r\n         \r\n            case 3:\r\n                echo "Kadra";\r\n            break;\r\n            \r\n            case 4:\r\n                echo "O nas";\r\n            break;\r\n            \r\n            case 5:\r\n                echo "Kontakt";\r\n            break;\r\n         \r\n            default:\r\n                echo "Aktualności";\r\n            break;\r\n        }\r\n    }\r\n    ?> \r\n</div>\r\n\r\n<div class = "container"> <!-- start całego cointainera -->\r\n    \r\n    <div class = "content"> \r\n    <?php\r\n    if (!isset($_GET[\'menu\']))\r\n        include(\'1.html\');\r\n    else\r\n    {    \r\n        $arg = (int)$_GET[\'menu\'];\r\n         \r\n        switch ($arg)\r\n        {\r\n            case 1:\r\n                include(\'1.html\');\r\n            break;\r\n         \r\n            case 2:\r\n                include(\'2.html\');\r\n            break;\r\n         \r\n            case 3:\r\n                include(\'3.html\');\r\n            break;\r\n            \r\n            case 4:\r\n                include(\'4.html\');\r\n            break;\r\n            \r\n            case 5:\r\n                include(\'5.html\');\r\n            break;\r\n         \r\n            default:\r\n                include(\'1.html\');\r\n            break;\r\n        }\r\n    }\r\n    ?>\r\n    </div>\r\n    \r\n</div> <!-- koniec całego cointainera -->\r\n\r\n</body>\r\n</html>\r\n\r\n'),
	('s4_style', '\r\nhtml, body\r\n{\r\n	margin: 0;\r\n	padding: 0;\r\n    background: rgb(240, 248, 255); /* Fall-back for browsers that don\'t\r\n                                        support rgba */\r\n    background: rgba(240, 248, 255, 0.3);\r\n}\r\n\r\n.head\r\n{\r\n  position: fixed;\r\n  width: 100%;\r\n  height: 15%;\r\n  background-color: #00FFFF;\r\n}\r\n\r\n.nav\r\n{\r\n  position: fixed;\r\n  width: 100%;\r\n  height: 6%;\r\n  background: rgb(0, 191, 255); /* Fall-back for browsers that don\'t\r\n                                    support rgba */\r\n  background: rgba(0, 191, 255, 0.6);\r\n  padding: 8px 8px;\r\n}\r\n\r\n.nav_btn\r\n{\r\n    background-color: #00BFFF; /* Green */\r\n    border: none;\r\n    color: blue;\r\n    padding: 15px 32px;\r\n    text-align: center;\r\n    text-decoration: none;\r\n    display: inline-block;\r\n    font-size: 18px;\r\n}\r\n\r\n.container\r\n{\r\n  width: 80%;\r\n  height: 90%;\r\n  top:14%;\r\n  position: fixed;\r\n  margin: 0 10% 0 10%;\r\n  background-color: #F0F8FF;\r\n  background-repeat: no-repeat;\r\n  background-size: cover;\r\n  color: blue;\r\n} \r\n\r\n.submenu\r\n{\r\n  top: 8%;\r\n  height: 3%;\r\n  width: 100%;\r\n  position: fixed;\r\n  background: aqua;\r\n  color: Dodgerblue;\r\n  font-size: 28px;\r\n  font-family: Courier new;\r\n  text-align: left;\r\n  padding: 1%;\r\n}\r\n\r\n.content\r\n{\r\n  position: fixed;\r\n  width: 60%;\r\n  height: 100%;\r\n  top: 14%;\r\n  left: 10%;\r\n  right: 20%;\r\n  background-color: transparent;\r\n  float: left;\r\n}\r\n'),
	('s4_style1', '\r\nhtml, body\r\n{\r\n	margin: 0;\r\n	padding: 0;\r\n    background: rgb(255, 218, 185); /* Fall-back for browsers that don\'t\r\n                                        support rgba */\r\n    background: rgba(255, 218, 185, 0.3);\r\n}\r\n\r\n.head\r\n{\r\n  position: fixed;\r\n  width: 100%;\r\n  height: 15%;\r\n  background-color: #00FFFF;\r\n}\r\n\r\n.nav\r\n{\r\n  position: fixed;\r\n  width: 100%;\r\n  height: 6%;\r\n  background: rgb(255, 140, 0); /* Fall-back for browsers that don\'t\r\n                                    support rgba */\r\n  background: rgba(255, 140, 0, 0.6);\r\n  padding: 8px 8px;\r\n}\r\n\r\n.nav_btn\r\n{\r\n    background-color: #FF8C00; /* Green */\r\n    border: none;\r\n    color: #FFFFF0;\r\n    padding: 15px 32px;\r\n    text-align: center;\r\n    text-decoration: none;\r\n    display: inline-block;\r\n    font-size: 18px;\r\n}\r\n\r\n.container\r\n{\r\n  width: 80%;\r\n  height: 90%;\r\n  top:14%;\r\n  position: fixed;\r\n  margin: 0 10% 0 10%;\r\n  background-color: #FFDAB9;\r\n  background-repeat: no-repeat;\r\n  background-size: cover;\r\n  color: Saddlebrown;\r\n} \r\n\r\n.submenu\r\n{\r\n  top: 8%;\r\n  height: 3%;\r\n  width: 100%;\r\n  position: fixed;\r\n  background: Bisque;\r\n  color: Saddlebrown;\r\n  font-size: 28px;\r\n  font-family: Courier new;\r\n  text-align: left;\r\n  padding: 1%;\r\n}\r\n\r\n.content\r\n{\r\n  position: fixed;\r\n  width: 60%;\r\n  height: 100%;\r\n  top: 14%;\r\n  left: 10%;\r\n  right: 20%;\r\n  background-color: transparent;\r\n  float: left;\r\n}\r\n');
;



DROP TABLE IF EXISTS `uzytkownicy`;
CREATE TABLE IF NOT EXISTS `uzytkownicy` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `login` varchar(14) NOT NULL,
  `haslo` varchar(14) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;